AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal local lambda setup

Resources:
  UrlShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: urlShortenHandler
      Handler: lambdas/urlShortenHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./lambdas/
      Events:
        ShortenAPI:
          Type: Api
          Properties:
            Path: /
            Method: post

  UrlRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: urlRedirectHandler
      Handler: lambdas/urlRedirectHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./lambdas/
      Events:
        RedirectAPI:
          Type: Api
          Properties:
            Path: /{id}
            Method: get
